services:
  movie-stream:
    build: .
    container_name: movie-stream
    restart: unless-stopped
    expose:
      - "8973"
    # Switch to Named Volumes
    volumes:
      - media_data:/app/media
      - tmp_data:/app/tmp
      - logs_data:/app/logs
    dns:
      - 8.8.8.8
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: movie-stream-nginx
    restart: unless-stopped
    ports:
      - "8973:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - media_data:/app/media:ro
      - tmp_data:/app/tmp:ro
    depends_on:
      - movie-stream

volumes:
  media_data:
  tmp_data:
  logs_data: